site_name: Code Notes

nav:
    - Home: index.md
    - General:
      - Git: gen/git-notes.md
    - Python:
        - General: py/py-general.md


theme:
    name: material
    highlightjs: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
